#
# NOTE: keep this synced with standard repo's config
#

name: Deploy
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - '.changeset/**'
      - 'packages/**'
      - '!examples/**'
      - '!.github/**'
      - '!.husky/**'
      - '!.vscode/**'
      - '!**/README.md'
      - '!**/CHANGELOG.md'
      - '!**/LICENSE'
      - '!packages/**/__tests__/**'
  pull_request:
    branches:
      - main
    paths:
      - '.changeset/**'
      - 'packages/**'
      - '!examples/**'
      - '!.github/**'
      - '!.husky/**'
      - '!.vscode/**'
      - '!**/README.md'
      - '!**/CHANGELOG.md'
      - '!**/LICENSE'
      - '!packages/**/__tests__/**'
env:
  TZ: "America/New_York"

jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup PNPM
        uses: pnpm/action-setup@v2.2.4
        with:
          version: 8

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'pnpm'

      - name: Setup Turbo cache
        uses: actions/cache@v3
        with:
          path: node_modules/.cache/turbo
          key: turbo-${{ github.job }}-${{ github.ref_name }}-${{ github.sha }}
          restore-keys: turbo-${{ github.job }}-${{ github.ref_name }}-

      - name: Install dependencies
        run: pnpm install

      - name: Lint
        run: pnpm run lint

      - name: Build
        run: pnpm run build

      # TODO: solve flaky tests
      # - name: Test
      #   run: pnpm run test

      - name: Deploy using ssh
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          port: ${{ secrets.PORT }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.PRIVATE_KEY }}
          script: |
            cd ~/home/git/deployment-test
            git pull origin master
            git status
            pnpm install --only=prod
            pm2 restart node1      